version: "2"
services: 
  api-gateway:
    container_name: api-gateway
    build: './API_Gateway'
    hostname: API_Gateway
    ports: 
      - "3001:3000"
    environment: 
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
    #restart: unless-stopped
    depends_on: 
      - waitforrabbit
      - nginx
      - rabbitmq

  match-service:
    container_name: match-service
    build: './Match_Service'
    hostname: Match_Service
    #restart: unless-stopped
    environment: 
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
      - MATCH_DB_CONNECTION_STRING=mongodb://db/one_day_matches_db
      - PROFILE_DB_CONNECTION_STRING=mongodb://db/one_day_profiles_db
      - MATCH_COUNT=15
    depends_on: 
      - waitforrabbit
      - db
      - rabbitmq

  profile-service:
    container_name: profile-service
    build: './Profile_Service'
    hostname: Profile_Service
    #restart: unless-stopped
    environment: 
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
      - PROFILE_DB_CONNECTION_STRING=mongodb://db/one_day_profiles_db
    depends_on: 
      - waitforrabbit
      - db
      - rabbitmq

  
  db:
    container_name: mongo-dependency
    image: mongo
    ports: 
      - "27017:27017"
   

  rabbitmq:
    container_name: rabbitmq-dependency
    image: rabbitmq:latest
    volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
            - 5672:5672
            - 15672:15672

  nginx:
    container_name: nginx-dependency
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes: 
      - ./public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
  
  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq 
    command: rabbitmq:5672