version: "2"
services: 
  api-gateway:
    container_name: api-gateway
    build: './API_Gateway'
    hostname: API_Gateway
    ports: 
      - "3000:3000"
    #restart: unless-stopped
    depends_on: 
      - nginx
    

  
  db:
    container_name: mongo-dependency
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/logs/:/var/log/rabbitmq/

  rabbitmq:
    container_name: rabbitmq-dependency
    image: rabbitmq:latest
    ports:
            - 5672:5672
            - 15672:15672

  nginx:
    container_name: nginx-dependency
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes: 
      - ./public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf