version: "2"
services: 
  api-gateway:
    container_name: api-gateway
    build: './API_Gateway'
    ports: 
      - "3000:3000"
    #restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on: 
      - nginx

  profile-service:
    container_name: profile-service
    build: './Profile_Service'
    #restart: unless-stopped
    depends_on: 
      - db
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  match-service:
    container_name: match-service
    build: './Match_Service'
    #restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on: 
      - db
    environment: 
      - MATCH_DB_CONNECTION_STRING=mongodb://db/one_day_matches_db
      - PROFILE_DB_CONNECTION_STRING=mongodb://db/one_day_profiles_db
      - MATCH_COUNT=15

  db:
    container_name: mongo-dependency
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/logs/:/var/log/rabbitmq/

  rabbitmq:
    container_name: rabbitmq-dependency
    image: rabbitmq:latest
    ports:
            - 5672:5672
            - 15672:15672

  nginx:
    container_name: nginx-dependency
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes: 
      - ./public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf